# Generated by Django 3.2.4 on 2021-09-02 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210827_1052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Blog Categories'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created',), 'verbose_name_plural': 'Blogs'},
        ),
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(default='default.png', upload_to='blog'),
        ),
    ]
