# Generated by Django 3.2.4 on 2021-09-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blog_intro',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
