# Generated by Django 3.2.4 on 2021-09-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_blog_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='appstore_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='made_at',
            field=models.CharField(default='.......', max_length=1000),
        ),
        migrations.AddField(
            model_name='project',
            name='playstore_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
