# Generated by Django 3.2.4 on 2021-09-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_project_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=300, upload_to='resume')),
            ],
            options={
                'verbose_name_plural': 'Resume',
            },
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-year',)},
        ),
    ]
