# Generated by Django 3.2.4 on 2021-09-27 17:21

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_resume_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='name',
            field=models.TextField(default='resume', max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(max_length=300, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='resume'),
        ),
    ]
