# Generated by Django 3.2.4 on 2021-09-27 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20210927_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='name',
        ),
    ]
